Repository angular/flex-layout, pull requests merged in 2018-04, with the labels that each got.

#699 docs: add breaking change for validateSuffixes
  CHANGELOG.md
Labels: P0, cla: yes, docs, pr: merge safe, pr: needs review

#701 build: add next target to release script
  release
Labels: build, cla: yes, pr: merge safe, pr: needs review

#706 feat(core): add validateBasis to core export
  src/lib/core/basis-validator/basis-validator.spec.ts
  src/lib/core/basis-validator/basis-validator.ts
  src/lib/core/public-api.ts
  src/lib/flex/flex/flex.ts
  src/lib/utils/index.ts
Labels: P1, cla: yes, feature, pr: needs review

#709 build: mark layout package as sideEffect-free for webpack v4
  src/lib/package.json
  tools/package-tools/entry-point-package-json.ts
Labels: cla: yes, pr: merge safe, pr: needs review

#710 build: switch release methods
  tools/gulp/gulpfile.ts
  tools/gulp/tasks/changelog.ts
  tools/gulp/tasks/publish.ts
  tools/gulp/tasks/validate-release.ts
Labels: cla: yes

#711 chore: bump the version to 6.0.0-beta.15
  package-lock.json
  package.json
Labels: cla: yes

#721 test(grid-gap): fix chrome 66 naming issue
  src/lib/grid/gap/gap.spec.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe, release: patch
