Repository angular/flex-layout, pull requests merged in 2018-07, with the labels that each got.

#772 chore: add descriptive comment for FlexLayoutModule
  src/lib/module.ts
Labels: cla: yes, docs, pr: merge safe, pr: needs review

#766 chore: remove Angular v6 instructions from README
  README.md
Labels: cla: yes, docs, pr: merge safe, pr: needs review

#795 build: fix browserstack mobile tests
  package-lock.json
  package.json
  test/browser-providers.js
  test/karma.conf.js
  test/remote_browsers.json
Labels: build, cla: yes, pr: merge safe, pr: needs review

#773 perf: remove duplicate function calls
  src/lib/core/base/base.ts
  src/lib/extended/show-hide/show-hide.ts
  src/lib/flex/flex-align/flex-align.ts
  src/lib/flex/flex-order/flex-order.ts
  src/lib/flex/flex/flex.ts
  src/lib/flex/layout-align/layout-align.ts
  src/lib/flex/layout/layout.ts
Labels: cla: yes, performance, pr: needs review

#794 build: move angular version to package.json
  build-config.js
  package.json
Labels: build, cla: yes, pr: merge safe, pr: needs review

#793 build: update testing configuration
  scripts/saucelabs/start-tunnel.sh
  test/karma-system-config.js
  test/karma-test-shim.js
  test/karma.conf.js
  test/protractor.conf.js
Labels: build, cla: yes, pr: merge safe, pr: needs review

#806 build: add git-semver-tags to dev dependencies
  package.json
Labels: build, cla: yes, pr: merge safe, pr: needs review

#807 build: fix random ngc resolve failures
  tools/package-tools/build-package.ts
  tools/package-tools/compile-entry-point.ts
  tools/package-tools/gulp/build-tasks-gulp.ts
Labels: build, cla: yes, pr: merge safe, pr: needs review

#809 fix: use correct xl breakpoint
  src/lib/core/breakpoints/data/break-points.ts
Labels: P0, cla: yes, pr: needs review

#780 docs: Adds note about default unit for fxFlex if none given
  docs/documentation/fxFlex-API.md
Labels: cla: yes, pr: needs rebase

#811 bump changelog to 6.0.0-beta.17
  CHANGELOG.md
  package.json
Labels: cla: yes
