Repository angular/flex-layout, pull requests merged in 2018-12, with the labels that each got.

#901 feat(flex): add support for rem units
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#905 build: switch to circleci
  .circleci/config.yml
  .travis.yml
  package.json
  release
  scripts/browserstack/start-tunnel.sh
  scripts/browserstack/stop-tunnel.sh
  scripts/browserstack/wait-tunnel.sh
  scripts/ci/README.md
  scripts/ci/env.sh
  scripts/ci/sources/mode.sh
  scripts/ci/sources/tunnel.sh
  scripts/ci/travis-deploy.sh
  scripts/ci/travis-env.sh
  scripts/ci/travis-script.sh
  scripts/ci/travis-testing.sh
  scripts/circleci/publish-snapshots.sh
  scripts/circleci/run-browserstack-tests.sh
  scripts/circleci/run-local-browser-tests.sh
  scripts/circleci/run-saucelabs-tests.sh
  scripts/closure-compiler/build-devapp-bundle.sh
  scripts/closure-compiler/tsconfig-rxjs.json
  scripts/deploy/publish-build-artifacts.sh
  scripts/release/README.md
  scripts/release/changelog.js
  scripts/release/releases.json
  scripts/retry-call.sh
  scripts/saucelabs/sauce_config.js
  scripts/saucelabs/start-tunnel.sh
  scripts/saucelabs/stop-tunnel.sh
  scripts/saucelabs/wait-tunnel.sh
  test/browser-providers.js
  test/karma-browsers.json
  test/karma.conf.js
  test/protractor.conf.js
  tools/gulp/tasks/aot.ts
  tools/gulp/tasks/ci.ts
  tools/gulp/tasks/hello-world.ts
  yarn.lock
Labels: build, cla: yes, pr: lgtm, pr: merge safe

#900 feat(core): add centralized media marshal service
  src/apps/demo-app/src/app/github-issues/split/split-area.directive.ts
  src/apps/demo-app/src/app/github-issues/split/split.directive.ts
  src/apps/universal-app/src/app/split/split-area.directive.ts
  src/apps/universal-app/src/app/split/split.directive.ts
  src/lib/core/add-alias.ts
  src/lib/core/base/base-adapter.ts
  src/lib/core/base/base.ts
  src/lib/core/base/base2.ts
  src/lib/core/base/index.ts
  src/lib/core/breakpoints/break-point.ts
  src/lib/core/breakpoints/breakpoint-tools.ts
  src/lib/core/breakpoints/data/break-points.ts
  src/lib/core/breakpoints/index.ts
  src/lib/core/match-media/mock/mock-match-media.ts
  src/lib/core/media-marshaller/media-marshaller.spec.ts
  src/lib/core/media-marshaller/media-marshaller.ts
  src/lib/core/media-monitor/media-monitor.ts
  src/lib/core/module.ts
  src/lib/core/public-api.ts
  src/lib/core/responsive-activation/responsive-activation.ts
  src/lib/extended/class/class.spec.ts
  src/lib/extended/class/class.ts
  src/lib/extended/img-src/img-src.ts
  src/lib/extended/module.ts
  src/lib/extended/show-hide/hide.spec.ts
  src/lib/extended/show-hide/show-hide.ts
  src/lib/extended/show-hide/show.spec.ts
  src/lib/extended/style/style.spec.ts
  src/lib/extended/style/style.ts
  src/lib/flex/flex-align/flex-align.ts
  src/lib/flex/flex-fill/flex-fill.ts
  src/lib/flex/flex-offset/flex-offset.spec.ts
  src/lib/flex/flex-offset/flex-offset.ts
  src/lib/flex/flex-order/flex-order.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
  src/lib/flex/layout-align/layout-align.ts
  src/lib/flex/layout-gap/layout-gap.ts
  src/lib/flex/layout/layout.ts
  src/lib/flex/module.ts
  src/lib/grid/align-columns/align-columns.ts
  src/lib/grid/align-rows/align-rows.ts
  src/lib/grid/area/area.ts
  src/lib/grid/areas/areas.ts
  src/lib/grid/auto/auto.ts
  src/lib/grid/column/column.ts
  src/lib/grid/columns/columns.ts
  src/lib/grid/gap/gap.ts
  src/lib/grid/grid-align/grid-align.ts
  src/lib/grid/module.ts
  src/lib/grid/row/row.ts
  src/lib/grid/rows/rows.ts
  src/lib/server/server-provider.ts
  yarn.lock
Labels: cla: yes, custom breakpoints, feature, performance, pr: needs review

#913 chore: update to 7.0.0-beta.20 with changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: merge safe

#916 fix(core): register all breakpoints at startup
  .circleci/config.yml
  src/lib/core/match-media/mock/mock-match-media.ts
  src/lib/core/media-marshaller/media-marshaller.ts
  src/lib/extended/show-hide/hide.spec.ts
  src/lib/extended/show-hide/show-hide.ts
Labels: cla: yes, pr: needs review

#917 chore: update to 7.0.0-beta.21 with changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: needs review

#919 fix(fxLayoutGap): respond correctly to layout changes
  src/lib/core/media-marshaller/media-marshaller.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
Labels: cla: yes, pr: needs review

#920 chore: add JSDoc to MediaChange
  src/lib/core/media-change.ts
Labels: cla: yes, docs, pr: merge safe

#923 fix(core): avoid race condition between registration and activation
  src/lib/core/media-marshaller/media-marshaller.ts
Labels: P0, cla: yes, pr: needs review

#921 fix(core): allow for breakpoints with periods in them
  src/lib/core/base/base2.ts
  src/lib/extended/show-hide/show-hide.ts
  src/lib/extended/show-hide/show.spec.ts
Labels: cla: yes, pr: needs review

#927 fix(core): clear recent styles after responsive deactivation
  src/lib/core/base/base2.ts
  src/lib/core/media-marshaller/media-marshaller.spec.ts
  src/lib/core/media-marshaller/media-marshaller.ts
  src/lib/extended/class/class.ts
  src/lib/extended/img-src/img-src.ts
  src/lib/extended/show-hide/show-hide.ts
  src/lib/extended/style/style.ts
  src/lib/flex/flex-align/flex-align.ts
  src/lib/flex/flex-offset/flex-offset.ts
  src/lib/flex/flex-order/flex-order.spec.ts
  src/lib/flex/flex-order/flex-order.ts
  src/lib/flex/flex/flex.ts
  src/lib/flex/layout-align/layout-align.ts
  src/lib/flex/layout-gap/layout-gap.ts
  src/lib/flex/layout/layout.ts
  src/lib/grid/align-columns/align-columns.ts
  src/lib/grid/align-rows/align-rows.ts
  src/lib/grid/area/area.ts
  src/lib/grid/areas/areas.ts
  src/lib/grid/auto/auto.ts
  src/lib/grid/column/column.ts
  src/lib/grid/columns/columns.ts
  src/lib/grid/gap/gap.ts
  src/lib/grid/grid-align/grid-align.ts
  src/lib/grid/row/row.ts
  src/lib/grid/rows/rows.ts
Labels: cla: yes

#939 fix(ngStyle): should work with preexisting styles
  src/lib/extended/style/style.spec.ts
  src/lib/extended/style/style.ts
Labels: cla: yes

#937 fix(core): avoid duplicate mediaQuery activations
  src/lib/core/media-marshaller/media-marshaller.spec.ts
  src/lib/core/media-marshaller/media-marshaller.ts
Labels: cla: yes, pr: needs review

#938 fix(ngStyle): do not truncate URLs
  src/lib/extended/style/style-transforms.spec.ts
  src/lib/extended/style/style-transforms.ts
  src/lib/extended/style/style.spec.ts
Labels: P0, cla: yes, pr: needs review

#940 feat(core): add static scss mixin
  package.json
  src/lib/core/sass/_layout-bp.scss
  stylelint-config.json
  tools/gulp/tasks/aot.ts
  tools/gulp/tasks/build-release.ts
  tools/gulp/tasks/clean.ts
  tools/gulp/tasks/development.ts
  tools/gulp/tasks/hello-world.ts
  tools/gulp/tasks/lint.ts
  tools/gulp/tasks/publish.ts
  tools/gulp/tasks/universal.ts
  tools/gulp/util/task-helpers.ts
  yarn.lock
Labels: cla: yes, feature, pr: needs review

#942 chore: update readme badge to reflect move to circleci
  README.md
Labels: cla: yes, pr: merge safe, pr: needs review

#912 chore: remove deprecated APIs
  src/apps/demo-app/src/app/media-query-status/media-query-status.component.ts
  src/apps/demo-app/src/app/responsive/responsive-row-column/responsive-row-column.component.ts
  src/lib/core/base/base-adapter.spec.ts
  src/lib/core/base/base-adapter.ts
  src/lib/core/base/base.ts
  src/lib/core/base/index.ts
  src/lib/core/media-monitor/index.ts
  src/lib/core/media-monitor/media-monitor.spec.ts
  src/lib/core/media-monitor/media-monitor.ts
  src/lib/core/module.ts
  src/lib/core/observable-media/index.ts
  src/lib/core/observable-media/observable-media.spec.ts
  src/lib/core/observable-media/observable-media.ts
  src/lib/core/public-api.ts
  src/lib/core/responsive-activation/responsive-activation.spec.ts
  src/lib/core/responsive-activation/responsive-activation.ts
  src/lib/extended/show-hide/show-hide.ts
Labels: build, cla: yes, pr: merge safe

#948 fix(show-hide): account for fxLayout on same element
  src/lib/extended/show-hide/hide.spec.ts
  src/lib/extended/show-hide/show-hide.ts
Labels: cla: yes, pr: lgtm

#962 fix(style): add SSR capabilities
  src/apps/universal-app/.editorconfig
  src/apps/universal-app/.gitignore
  src/apps/universal-app/README.md
  src/apps/universal-app/angular.json
  src/apps/universal-app/e2e/protractor.conf.js
  src/apps/universal-app/e2e/src/app.e2e-spec.ts
  src/apps/universal-app/e2e/src/app.po.ts
  src/apps/universal-app/e2e/tsconfig.e2e.json
  src/apps/universal-app/package.json
  src/apps/universal-app/server.ts
  src/apps/universal-app/src/app/app.component.html
  src/apps/universal-app/src/browserslist
  src/apps/universal-app/src/environments/environment.ts
  src/apps/universal-app/src/karma.conf.js
  src/apps/universal-app/src/main.ts
  src/apps/universal-app/src/polyfills.ts
  src/apps/universal-app/src/tsconfig.app.json
  src/apps/universal-app/src/tsconfig.server.json
  src/apps/universal-app/src/tsconfig.spec.json
  src/apps/universal-app/src/tslint.json
  src/apps/universal-app/src/typings.d.ts
  src/apps/universal-app/tsconfig.json
  src/apps/universal-app/tslint.json
  src/apps/universal-app/webpack.server.config.js
  src/lib/extended/style/style.ts
  tools/gulp/tasks/universal.ts
Labels: cla: yes, pr: needs review, ssr

#955 fix(core): improve use of breakpoint priorities
  .gitignore
  src/lib/core/breakpoints/break-point-registry.spec.ts
  src/lib/core/breakpoints/break-point-registry.ts
  src/lib/core/breakpoints/break-point.ts
  src/lib/core/breakpoints/breakpoint-tools.spec.ts
  src/lib/core/breakpoints/breakpoint-tools.ts
  src/lib/core/breakpoints/data/break-points.spec.ts
  src/lib/core/breakpoints/data/break-points.ts
  src/lib/core/breakpoints/data/orientation-break-points.spec.ts
  src/lib/core/breakpoints/data/orientation-break-points.ts
  src/lib/core/breakpoints/index.ts
  src/lib/core/match-media/match-media.spec.ts
  src/lib/core/match-media/match-media.ts
  src/lib/core/match-media/mock/mock-match-media.spec.ts
  src/lib/core/match-media/mock/mock-match-media.ts
  src/lib/core/match-media/server-match-media.ts
  src/lib/core/media-marshaller/media-marshaller.spec.ts
  src/lib/core/media-marshaller/media-marshaller.ts
  src/lib/core/media-observer/media-observer.spec.ts
  src/lib/core/media-observer/media-observer.ts
  src/lib/extended/class/class.spec.ts
  src/lib/extended/show-hide/show.spec.ts
  src/lib/flex/flex-offset/flex-offset.spec.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/layout-align/layout-align.spec.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout/layout.spec.ts
  src/lib/server/server-provider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready
