Repository angular/flex-layout, pull requests merged in 2018-03, with the labels that each got.

#643 Fix RegExp Issue in older versions of Safari
  src/lib/core/browser-provider.ts
Labels: cla: no, pr: lgtm, pr: needs squash

#649 build: switch to separate BrowserStack license
  .travis.yml
Labels: cla: yes

#629 fix(fxFlex): apply correct flex-basis stylings
  src/lib/core/style-utils/style-utils.ts
  src/lib/core/stylesheet-map.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
Labels: cla: yes, flexbox, pr: needs review

#650 build: add sample Circle CI config
  .circleci/config.yml
Labels: build, cla: yes, pr: needs review

#659 fix(ssr): fix lazy-loading functionality
  src/lib/core/match-media/match-media-provider.ts
  src/lib/core/module.ts
  src/lib/core/public-api.ts
  src/lib/core/style-utils/style-utils.spec.ts
  src/lib/core/style-utils/style-utils.ts
  src/lib/core/stylesheet-map/index.ts
  src/lib/core/stylesheet-map/stylesheet-map-provider.ts
  src/lib/core/stylesheet-map/stylesheet-map.ts
  src/lib/extended/module.ts
  src/lib/flex/module.ts
Labels: P1: urgent, cla: yes, pr: needs review, ssr

#653 docs(custom-breakpoints): fix broken links, typos
  docs/documentation/Custom-Breakpoints.md
Labels: cla: yes, docs, pr: lgtm, pr: merge safe

#658 fix(fxFlex): make sure not to set width/height when flex is default
  src/apps/demo-app/package-lock.json
  src/lib/core/match-media/match-media-provider.ts
  src/lib/core/module.ts
  src/lib/extended/module.ts
  src/lib/flex/flex/flex.ts
  src/lib/flex/module.ts
  tools/gulp/tasks/development.ts
Labels: P1: urgent, build, cla: yes, flexbox, pr: needs review

#664 docs(lib): update links to reflect library refactor
  README.md
  docs/documentation/Adaptive-Layouts.md
  docs/documentation/Use-Cases.md
  docs/documentation/Using-Angular-CLI.md
  docs/documentation/_Sidebar.md
  docs/documentation/fxFlex-API.md
  docs/documentation/fxFlexAlign-API.md
  docs/documentation/fxFlexFill-API.md
  docs/documentation/fxFlexOffset-API.md
  docs/documentation/fxFlexOrder-API.md
  docs/documentation/fxLayout-API.md
  docs/documentation/fxLayoutAlign-API.md
  docs/documentation/fxLayoutGap-API.md
  docs/documentation/imgSrc-API.md
  docs/documentation/ngClass-API.md
  docs/documentation/ngStyle-API.md
Labels: P0: critical, cla: yes, docs, pr: merge safe, pr: needs review

#662 fix(fxFlex): fix wrapping in older versions of Safari
  src/apps/demo-app/src/app/github-issues/issue-266/issue-266.component.html
  src/lib/flex/flex-offset/flex-offset.spec.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
  tools/gulp/tasks/development.ts
Labels: cla: yes, flexbox, pr: needs review, tests

#673 docs: fix broken links
  docs/documentation/Performance-Considerations.md
  docs/documentation/fxLayoutGap-API.md
Labels: cla: yes, docs, pr: merge safe, pr: needs review

#670 feat(tokens): add configuration for breakpoints and flex styles
  docs/documentation/BreakPoints.md
  src/lib/core/breakpoints/break-point-registry.ts
  src/lib/core/breakpoints/break-points-provider.ts
  src/lib/core/breakpoints/breakpoint-tools.spec.ts
  src/lib/core/breakpoints/breakpoint-tools.ts
  src/lib/core/breakpoints/data/orientation-break-points.spec.ts
  src/lib/core/match-media/match-media.spec.ts
  src/lib/core/match-media/mock/mock-match-media.spec.ts
  src/lib/core/media-monitor/media-monitor.spec.ts
  src/lib/core/module.ts
  src/lib/core/observable-media/observable-media.spec.ts
  src/lib/core/public-api.ts
  src/lib/core/responsive-activation/responsive-activation.spec.ts
  src/lib/core/style-utils/style-utils.ts
  src/lib/core/tokens/breakpoint-token.ts
  src/lib/core/tokens/flex-styles-token.ts
  src/lib/core/tokens/index.ts
  src/lib/core/tokens/server-token.ts
  src/lib/core/tokens/vendor-prefixes-token.ts
  src/lib/extended/class/class.spec.ts
  src/lib/extended/img-src/img-src.spec.ts
  src/lib/extended/show-hide/hide.spec.ts
  src/lib/extended/show-hide/show.spec.ts
  src/lib/extended/style/style.spec.ts
  src/lib/flex/flex-offset/flex-offset.spec.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
  src/lib/flex/layout-align/layout-align.spec.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout/layout.spec.ts
Labels: cla: yes, discussion, feature, pr: needs review

#672 fix(demo-app): add polyfills for IE11 to demo-app
  src/apps/demo-app/src/polyfills.ts
Labels: P0: critical, cla: yes, docs, pr: merge safe, pr: needs review

#677 feat(demo-app): use/register custom breakpoints
  src/apps/demo-app/package-lock.json
  src/apps/demo-app/src/app/app.module.ts
  src/lib/module.ts
Labels: build, cla: yes, docs, pr: needs review

#678 build: remove apps package-locks from git
  .gitignore
  src/apps/demo-app/package-lock.json
  src/apps/hello-world/package-lock.json
Labels: build, cla: yes, pr: merge safe, pr: needs review

#669 fix(fxFlex): fix non-wrapping behavior and default fxFlex value
  src/lib/flex/flex-offset/flex-offset.spec.ts
  src/lib/flex/flex-offset/flex-offset.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
  src/lib/flex/layout-align/layout-align.ts
  src/lib/flex/layout-gap/layout-gap.ts
  src/lib/flex/layout/layout.ts
Labels: cla: yes, flexbox, pr: needs review

#667 feat(fxLayoutGap): add gutter functionality to layout-gap
  src/apps/demo-app/src/app/layout/docs-layout/docs-layout.component.ts
  src/apps/demo-app/src/app/layout/layout-gap/layout-gap.component.spec.ts
  src/apps/demo-app/src/app/layout/layout-gap/layout-gap.component.ts
  src/apps/demo-app/src/app/layout/layout.module.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout-gap/layout-gap.ts
Labels: cla: yes, discussion, feature, pr: needs review

#680 fix(breakpoints): add global provider for BreakPointRegistry
  src/lib/core/breakpoints/break-point-registry-provider.ts
  src/lib/core/module.ts
Labels: P0: critical, cla: yes, pr: needs review

#683 fix(demo-app): fix sizing for layout-gap demo
  src/apps/demo-app/src/app/layout/layout-gap/layout-gap.component.ts
Labels: cla: yes, docs, pr: merge safe, pr: needs review

#682 fix(fxLayoutGap): add proper gaps for reverse dir
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout-gap/layout-gap.ts
Labels: cla: yes, pr: needs review

#687 feat(demo-app): add version number to header
  src/apps/demo-app/src/app/app.component.html
  src/apps/demo-app/src/app/app.component.ts
Labels: cla: yes, docs, pr: merge safe, pr: needs review

#690 Minor content fix (duplicate word)
  docs/documentation/Adaptive-Layouts.md
Labels: cla: yes, docs, pr: lgtm, pr: merge safe
