Repository angular/flex-layout, pull requests merged in 2018-11, with the labels that each got.

#883 docs: fix minor grammer and use single-quotes in examples
  docs/documentation/ObservableMedia.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#845 fix(fxLayoutAlign): add space-between and space-around options
  src/lib/flex/layout-align/layout-align.spec.ts
  src/lib/flex/layout-align/layout-align.ts
Labels: cla: yes, feature, flexbox, pr: lgtm

#881 fix(show-hide): work with Angular components and elements without fxLayout
  package-lock.json
  package.json
  src/lib/core/style-utils/style-utils.spec.ts
  src/lib/core/style-utils/style-utils.ts
  src/lib/extended/show-hide/hide.spec.ts
  src/lib/extended/show-hide/show-hide.ts
  src/lib/extended/show-hide/show.spec.ts
  src/lib/utils/testing/custom-matchers.ts
  test/karma-system-config.js
  tools/package-tools/rollup-globals.ts
Labels: P0, cla: yes, pr: lgtm

#884 feat(core): add ability to override style building
  src/lib/core/base/base.ts
  src/lib/core/public-api.ts
  src/lib/core/style-builder/style-builder.ts
  src/lib/flex/flex-align/flex-align.ts
  src/lib/flex/flex-fill/flex-fill.ts
  src/lib/flex/flex-offset/flex-offset.spec.ts
  src/lib/flex/flex-offset/flex-offset.ts
  src/lib/flex/flex-order/flex-order.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
  src/lib/flex/layout-align/layout-align.spec.ts
  src/lib/flex/layout-align/layout-align.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout-gap/layout-gap.ts
  src/lib/flex/layout/layout.spec.ts
  src/lib/flex/layout/layout.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#895 docs: minor spelling fixes
  docs/documentation/fxHide-API.md
  docs/documentation/fxShow-API.md
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#888 feat(core): add memoization to style generation
  src/lib/core/base/base.ts
  src/lib/core/style-builder/style-builder.ts
  src/lib/flex/flex-align/flex-align.ts
  src/lib/flex/flex-fill/flex-fill.ts
  src/lib/flex/flex-offset/flex-offset.spec.ts
  src/lib/flex/flex-offset/flex-offset.ts
  src/lib/flex/flex-order/flex-order.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
  src/lib/flex/layout-align/layout-align.spec.ts
  src/lib/flex/layout-align/layout-align.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout-gap/layout-gap.ts
  src/lib/flex/layout/layout.spec.ts
  src/lib/flex/layout/layout.ts
Labels: cla: yes, feature, pr: needs review
