Repository angular/flex-layout, pull requests merged in 2018-02, with the labels that each got.

#611 build: add tslint rule to enforce deletion targets
  tools/tslint-rules/deletionTargetRule.ts
  tslint.json
Labels: build, cla: yes, pr: merge safe, pr: needs review

#612 build: don't skip master build when only md files have changed
  scripts/ci/travis-testing.sh
Labels: build, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#527 fix: apply correct RTL margins
  src/demo-app/app/docs-layout/_module.ts
  src/demo-app/app/docs-layout/layoutRowWithDirection.demo.ts
  src/lib/api/flexbox/flex-offset.spec.ts
  src/lib/api/flexbox/flex-offset.ts
  src/lib/api/flexbox/layout-gap.spec.ts
  src/lib/api/flexbox/layout-gap.ts
  src/lib/bidi/bidi-module.ts
  src/lib/bidi/bidi.md
  src/lib/bidi/dir.ts
  src/lib/bidi/directionality.spec.ts
  src/lib/bidi/directionality.ts
  src/lib/bidi/index.ts
  src/lib/bidi/public-api.ts
  src/lib/module.ts
Labels: cla: yes, pr: lgtm, related: material2

#618 build: conditional travis build stages
  .travis.yml
  scripts/ci/travis-deploy.sh
  scripts/ci/travis-env.sh
  scripts/ci/travis-script.sh
Labels: build, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#614 build: enforce that deprecated APIs have a deletion target
  tools/tslint-rules/deletionTargetRule.ts
Labels: build, cla: yes, pr: merge safe, pr: needs review

#623 fix(layout-gap): apply correct gaps based on flex order
  src/lib/api/flexbox/layout-gap.spec.ts
  src/lib/api/flexbox/layout-gap.ts
Labels: cla: yes, pr: lgtm

#626 docs: add Universal app changes to documentation
  docs/documentation/Developer-Setup.md
  docs/documentation/Live-Demos.md
  package-lock.json
  package.json
  src/apps/universal-app/package-lock.json
  src/lib/bidi/README.md
  src/lib/server/README.md
  tools/gulp/tasks/universal.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge safe

#633 fix(release): Fix release script by removing ',' of the last item in …
  release
Labels: build, cla: yes, pr: merge safe, pr: needs review

#634 build: add package name to AMD modules
  package-lock.json
  package.json
  tools/package-tools/build-bundles.ts
Labels: build, cla: yes, pr: merge safe, pr: needs review
