Repository angular/flex-layout, pull requests merged in 2018-10, with the labels that each got.

#853 fix(module): do not require breakpoints in withConfig
  .gitignore
  src/lib/module.ts
Labels: P0, cla: yes, pr: lgtm, pr: merge ready

#858 chore: remove deletion target candidates
  src/lib/core/match-media/match-media-provider.ts
  src/lib/core/media-monitor/index.ts
  src/lib/core/media-monitor/media-monitor-provider.ts
  src/lib/core/observable-media/index.ts
  src/lib/core/observable-media/observable-media-provider.ts
  src/lib/core/stylesheet-map/index.ts
  src/lib/core/stylesheet-map/stylesheet-map-provider.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#857 chore: update package.json to 7.0.0-beta.19 w/ changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: lgtm, pr: merge safe, pr: needs cleanup/tests

#860 feat: upgrade to TypeScript v3.1
  package-lock.json
  package.json
  src/apps/demo-app/.angular-cli.json
  src/apps/demo-app/angular.json
  src/apps/demo-app/karma.conf.js
  src/apps/demo-app/package.json
  src/apps/demo-app/src/polyfills.ts
  src/apps/demo-app/src/tsconfig.spec.json
  src/apps/demo-app/tsconfig.json
  src/apps/hello-world/.angular-cli.json
  src/apps/hello-world/angular.json
  src/apps/hello-world/package.json
  src/apps/hello-world/src/polyfills.ts
  src/apps/hello-world/tsconfig.json
  src/apps/universal-app/.angular-cli.json
  src/apps/universal-app/angular.json
  src/apps/universal-app/karma.conf.js
  src/apps/universal-app/package.json
  src/apps/universal-app/server.ts
  src/apps/universal-app/src/polyfills.ts
  src/apps/universal-app/src/tsconfig.spec.json
  src/apps/universal-app/tsconfig.json
  src/lib/core/match-media/match-media.ts
  src/lib/core/match-media/mock/mock-match-media.ts
  src/lib/core/match-media/server-match-media.ts
  src/lib/core/responsive-activation/responsive-activation.spec.ts
  src/lib/server/server-provider.ts
  src/lib/tsconfig-tests.json
Labels: build, cla: yes, pr: merge ready

#863 docs: remove extraneous word
  docs/documentation/API-Documentation.md
Labels: cla: yes, docs, pr: merge ready, pr: merge safe
