Repository angular/flex-layout, pull requests merged in 2019-05, with the labels that each got.

#1056 build: upgrade to Angular and Components v8
  package.json
  src/apps/demo-app/package.json
  src/apps/hello-world/package.json
  src/apps/universal-app/package.json
  src/lib/extended/class/class.ts
  src/lib/extended/style/style.ts
  src/lib/package.json
  yarn.lock
Labels: cla: yes, pr: merge safe

#1062 chore: update to 8.0.0-beta.25 with changelog
  CHANGELOG.md
  package.json
  src/lib/core/media-observer/media-observer.ts
Labels: cla: yes, pr: merge safe

#1068 build: upgrade to Angular v8 final RC w/ release fix
  CHANGELOG.md
  package.json
  src/apps/demo-app/package.json
  src/apps/demo-app/src/app/github-issues/split/split.directive.ts
  src/apps/hello-world/package.json
  src/apps/universal-app/package.json
  src/apps/universal-app/src/app/split/split.directive.ts
  src/lib/flex/flex/flex.spec.ts
  tools/package-tools/compile-entry-point.ts
  yarn.lock
Labels: build, cla: yes, pr: merge safe

#1075 fix(core): update breakpoint ranges to avoid overlapping
  src/lib/core/breakpoints/data/break-points.ts
  src/lib/core/breakpoints/data/orientation-break-points.ts
  src/lib/core/media-observer/media-observer.spec.ts
  src/lib/core/sass/_layout-bp.scss
Labels: cla: yes, pr: merge ready
