Repository angular/flex-layout, pull requests merged in 2019-09, with the labels that each got.

#1116 chore: enable automatic locking of closed and inactive issue
  .github/workflows/lock-closed.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#1117 ci: move to latest lock-closed commit for github action
  .github/workflows/lock-closed.yml
Labels: cla: yes, pr: merge safe

#1121 ci: update lock-closed to only run once per day
  .github/workflows/lock-closed.yml
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#1125 chore: remove package-lock
  package-lock.json
Labels: cla: yes
