Repository angular/flex-layout, pull requests merged in 2019-03, with the labels that each got.

#1031 Fail-safe handling of nullable string value in lookupStyle
  src/lib/core/style-utils/style-utils.ts
Labels: cla: yes, pr: lgtm, pr: merge ready

#1036 fix(layout-align): respect inline-flex on sibling fxLayout
  src/lib/flex/layout-align/layout-align.spec.ts
  src/lib/flex/layout-align/layout-align.ts
Labels: cla: yes

#1037 fix(fxLayoutGap): correctly handle lack of fallback value
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout-gap/layout-gap.ts
Labels: cla: yes

#1038 fix(fxFlex): restore correct styles after fxLayoutAlign is applied
  src/lib/flex/flex/flex.ts
  src/lib/flex/layout-align/layout-align.spec.ts
Labels: cla: yes

#1039 chore: update to 7.0.0-beta.24 with changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: cla: yes, pr: merge safe
