Repository angular/flex-layout, pull requests merged in 2019-11, with the labels that each got.

#1142 build: fix gulp setup not working with node v12
  .circleci/config.yml
  package.json
  src/apps/demo-app/package.json
  src/apps/hello-world/package.json
  src/apps/universal-app/package.json
  src/lib/grid/auto/auto.spec.ts
  tools/gulp/tasks/universal.ts
  yarn.lock
Labels: build, cla: yes, pr: merge safe

#1144 test: remove unused architect targets from test app
  src/apps/hello-world/angular.json
  src/apps/hello-world/package.json
Labels: build, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#1080 feat(core): support beforeprint and afterprint hooks
  src/lib/core/media-marshaller/print-hook.ts
Labels: P2, cla: yes, pr: needs review

#1145 chore: force LF as linebreak-style when checking out the repo
  .gitattributes
Labels: cla: yes

#1153 fix(ssr): reset class counter to zero before each render
  src/lib/server/server-provider.ts
Labels: cla: yes, ssr
