Repository angular/flex-layout, pull requests merged in 2019-01, with the labels that each got.

#954 feat(core): add print support with mediaQuery override
  docs/documentation/BreakPoints.md
  docs/documentation/fxHide-API.md
  docs/documentation/fxShow-API.md
  src/apps/demo-app/src/app/app.component.html
  src/apps/demo-app/src/app/app.module.ts
  src/apps/demo-app/src/app/responsive/docs-responsive/docs-responsive.component.ts
  src/apps/demo-app/src/app/watermark.component.scss
  src/apps/demo-app/src/app/watermark.component.ts
  src/apps/demo-app/src/styles.scss
  src/lib/core/add-alias.ts
  src/lib/core/base/base2.ts
  src/lib/core/breakpoints/break-point-registry.ts
  src/lib/core/breakpoints/breakpoint-tools.ts
  src/lib/core/breakpoints/data/orientation-break-points.spec.ts
  src/lib/core/breakpoints/data/orientation-break-points.ts
  src/lib/core/match-media/match-media.spec.ts
  src/lib/core/match-media/mock/mock-match-media.spec.ts
  src/lib/core/match-media/mock/mock-match-media.ts
  src/lib/core/media-marshaller/media-marshaller.spec.ts
  src/lib/core/media-marshaller/media-marshaller.ts
  src/lib/core/media-marshaller/print-hook.ts
  src/lib/core/media-observer/media-observer.spec.ts
  src/lib/core/media-observer/media-observer.ts
  src/lib/core/public-api.ts
  src/lib/core/tokens/library-config.ts
  src/lib/extended/class/class.spec.ts
  src/lib/extended/show-hide/hide.spec.ts
  src/lib/extended/show-hide/show-hide.ts
  src/lib/extended/show-hide/show.spec.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/grid/grid-align/grid-align.spec.ts
  src/lib/module.ts
Labels: P1, cla: yes, pr: lgtm, pr: merge ready

#965 chore: bump year
  LICENSE
Labels: cla: yes, pr: merge safe, pr: needs review

#976 build: upgrade to Angular v7.2 and TypeScript v3.2
  .gitignore
  package.json
  src/lib/core/match-media/mock/mock-match-media.ts
  src/lib/core/match-media/server-match-media.ts
  yarn.lock
Labels: build, cla: yes, pr: lgtm, pr: merge safe, pr: needs review

#978 build: UMD module references incorrect flex-layout globals
  tools/gulp/packages.ts
  tools/package-tools/build-bundles.ts
  tools/package-tools/build-package.ts
  tools/package-tools/build-release.ts
  tools/package-tools/rollup-globals.ts
Labels: build, cla: yes, pr: merge ready, pr: merge safe

#968 chore: update to 7.0.0-beta.23 with changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: merge safe, pr: needs review

#980 build: upgrade to zone.js v0.8.27
  package.json
  yarn.lock
Labels: build, cla: yes, pr: lgtm, pr: merge safe

#982 docs: make splitter work in IE
  src/apps/demo-app/src/app/github-issues/split/split-handle.directive.ts
  src/apps/demo-app/src/app/github-issues/split/split.directive.ts
Labels: cla: yes, docs, pr: lgtm, pr: merge safe

#969 fix(extended): add demo to show fxHide with used with custom breakpoint
  package.json
  src/apps/demo-app/src/app/app.module.ts
  src/apps/demo-app/src/app/stack-overflow/hide-custom-bp/hide-custom-bp.component.scss
  src/apps/demo-app/src/app/stack-overflow/hide-custom-bp/hide-with-custom-bp.component.ts
  src/apps/demo-app/src/app/stack-overflow/stack-overflow.module.ts
  src/apps/demo-app/src/app/stack-overflow/stack-overflow/stack-overflow.component.ts
  src/apps/demo-app/src/styles.scss
  yarn.lock
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#983 fix(fxLayoutGap): not working with dynamic fxHide
  src/lib/core/base/base2.ts
  src/lib/core/media-marshaller/media-marshaller.spec.ts
  src/lib/core/media-marshaller/media-marshaller.ts
  src/lib/extended/show-hide/show-hide.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout-gap/layout-gap.ts
Labels: P1, cla: yes, pr: lgtm

#986 fix(img-src): correctly initialize fallback value
  src/lib/extended/img-src/img-src.spec.ts
  src/lib/extended/img-src/img-src.ts
Labels: P1, cla: yes, pr: lgtm

#987 fix(sass): update stylesheet with correct keys
  src/lib/core/sass/_layout-bp.scss
Labels: cla: yes, pr: lgtm

#988 test(ssr): fix SSR flakes and change matchMedia variable name
  src/lib/core/breakpoints/data/orientation-break-points.spec.ts
  src/lib/core/match-media/match-media.spec.ts
  src/lib/core/match-media/match-media.ts
  src/lib/core/match-media/mock/mock-match-media.spec.ts
  src/lib/core/media-marshaller/media-marshaller.spec.ts
  src/lib/core/media-observer/media-observer.spec.ts
  src/lib/extended/class/class.spec.ts
  src/lib/extended/img-src/img-src.spec.ts
  src/lib/extended/show-hide/hide.spec.ts
  src/lib/extended/show-hide/show.spec.ts
  src/lib/extended/style/style.spec.ts
  src/lib/flex/flex-order/flex-order.spec.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/layout-align/layout-align.spec.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout/layout.spec.ts
  src/lib/grid/align-columns/align-columns.spec.ts
  src/lib/grid/align-rows/align-rows.spec.ts
  src/lib/grid/area/area.spec.ts
  src/lib/grid/areas/areas.spec.ts
  src/lib/grid/auto/auto.spec.ts
  src/lib/grid/column/column.spec.ts
  src/lib/grid/columns/columns.spec.ts
  src/lib/grid/gap/gap.spec.ts
  src/lib/grid/grid-align/grid-align.spec.ts
  src/lib/grid/row/row.spec.ts
  src/lib/grid/rows/rows.spec.ts
  src/lib/server/server-provider.ts
Labels: cla: yes, pr: needs review

#990 test(imgrsc): fix use of mediaController variable
  src/lib/extended/img-src/img-src.spec.ts
Labels: build, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#994 fix(core): MediaObserver can report 1..n activations
  src/apps/demo-app/src/app/media-query-status/media-query-status.component.ts
  src/apps/demo-app/src/app/responsive/responsive-row-column/responsive-row-column.component.ts
  src/lib/core/add-alias.ts
  src/lib/core/match-media/match-media.spec.ts
  src/lib/core/match-media/match-media.ts
  src/lib/core/media-change.ts
  src/lib/core/media-observer/media-observer.spec.ts
  src/lib/core/media-observer/media-observer.ts
  src/lib/core/public-api.ts
  tslint.json
Labels: cla: yes, pr: needs review

#995 fix(ngClass): should properly remove classes without fallback
  src/lib/extended/class/class.spec.ts
  src/lib/extended/class/class.ts
Labels: P1, cla: yes, pr: needs review

#998 feat(core): move MatchMedia to internal scope
  src/lib/core/match-media/index.ts
  src/lib/core/public-api.ts
  src/lib/extended/class/class.spec.ts
  src/lib/extended/img-src/img-src.spec.ts
  src/lib/extended/show-hide/hide.spec.ts
  src/lib/extended/show-hide/show.spec.ts
  src/lib/extended/style/style.spec.ts
  src/lib/flex/flex-offset/flex-offset.spec.ts
  src/lib/flex/flex-order/flex-order.spec.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/layout-align/layout-align.spec.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout/layout.spec.ts
  src/lib/grid/align-columns/align-columns.spec.ts
  src/lib/grid/align-rows/align-rows.spec.ts
  src/lib/grid/area/area.spec.ts
  src/lib/grid/areas/areas.spec.ts
  src/lib/grid/auto/auto.spec.ts
  src/lib/grid/column/column.spec.ts
  src/lib/grid/columns/columns.spec.ts
  src/lib/grid/gap/gap.spec.ts
  src/lib/grid/grid-align/grid-align.spec.ts
  src/lib/grid/row/row.spec.ts
  src/lib/grid/rows/rows.spec.ts
  src/lib/server/server-match-media.ts
  src/lib/server/server-provider.ts
Labels: cla: yes, pr: lgtm

#997 feat(core): implement MediaTrigger to allow manual activations
  src/lib/core/README.md
  src/lib/core/match-media/match-media.ts
  src/lib/core/match-media/mock/mock-match-media.ts
  src/lib/core/media-trigger/index.ts
  src/lib/core/media-trigger/media-trigger.spec.ts
  src/lib/core/media-trigger/media-trigger.ts
  src/lib/core/public-api.ts
  src/lib/core/tokens/library-config.ts
  src/lib/server/server-match-media.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#999 feat(server): allow ability to specify breakpoints to activate on server
  src/lib/core/tokens/library-config.ts
  src/lib/server/server-provider.ts
Labels: cla: yes, pr: needs review, ssr

#1004 fix(core): update breakpoint ranges to remove subpixel gaps
  src/lib/core/breakpoints/data/break-points.ts
  src/lib/core/media-observer/media-observer.spec.ts
  src/lib/core/sass/_layout-bp.scss
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#1007 docs: add a Getting Started section to the README
  README.md
Labels: cla: yes, docs, pr: merge ready, pr: merge safe
