Repository angular/flex-layout, pull requests merged in 2020-03, with the labels that each got.

#1218 build: add missing return type for strict mode
  src/lib/core/media-trigger/media-trigger.ts
Labels: build, cla: yes

#1220 fix(orientation): use tablet landscape screen type
  src/lib/core/breakpoints/data/orientation-break-points.ts
Labels: cla: yes, pr: lgtm, pr: merge ready, pr: merge safe

#1226 build: do not include secondary entry-points in primary UMD bundle
  tools/package-tools/build-bundles.ts
Labels: build, cla: yes, pr: lgtm, pr: merge ready, pr: merge safe
