Repository angular/flex-layout, pull requests merged in 2020-05, with the labels that each got.

#1235 fix(print-hook): unregister event listeners on destroy
  src/lib/core/media-marshaller/print-hook.ts
Labels: cla: yes

#1234 feat(layout-gap): add x/y options for grid mode
  src/apps/demo-app/src/app/layout/layout-gap/layout-gap.component.ts
  src/lib/flex/layout-gap/layout-gap.spec.ts
  src/lib/flex/layout-gap/layout-gap.ts
Labels: cla: yes

#1237 fix(flex): wait for parent element until template is initialized
  src/lib/core/base/base2.ts
  src/lib/core/style-utils/style-utils.ts
  src/lib/flex/flex/flex.spec.ts
  src/lib/flex/flex/flex.ts
Labels: cla: yes

#1225 docs: fix HTML closing tags for fxFlex API page
  docs/documentation/fxFlex-API.md
Labels: cla: yes, docs, pr: lgtm, pr: merge ready, pr: merge safe

#1238 build: use no async option for ngcc
  package.json
Labels: build, cla: yes, pr: merge safe

#1240 build: upgrade to Angular v9.1, CDK v9.2, and TypeScript 3.8
  package.json
  src/lib/core/match-media/mock/mock-match-media.ts
  src/lib/server/server-match-media.ts
  src/lib/tsconfig-build.json
  yarn.lock
Labels: build, cla: yes, pr: merge safe

#1243 fix(show-hide): use initial value as fallback instead of parent
  src/lib/extended/show-hide/show-hide.ts
  src/lib/extended/show-hide/show.spec.ts
Labels: cla: yes

#1244 fix(media-observer): return correct value for isActive on init
  src/lib/core/match-media/match-media.ts
  src/lib/core/media-observer/media-observer.spec.ts
  src/lib/core/media-observer/media-observer.ts
Labels: cla: yes

#1245 fix(media-marshaller): do not propagate undefined value
  src/lib/core/media-marshaller/media-marshaller.ts
  src/lib/extended/class/class.spec.ts
Labels: cla: yes

#1246 fix(core): only trigger style updates when value changes
  src/lib/core/base/base2.ts
Labels: cla: yes, performance

#1247 fix(core): ignore null values in breakpoint fallback mechanism
  src/lib/core/media-marshaller/media-marshaller.ts
Labels: cla: yes

#1236 fix(match-media): unregister media query event listeners on destroy
  src/lib/core/match-media/match-media.ts
  src/lib/core/media-trigger/media-trigger.spec.ts
  src/lib/core/media-trigger/media-trigger.ts
Labels: cla: yes

#1248 chore: update to 9.0.0-beta.30 with changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: merge safe

#1251 Revert "fix(show-hide): use initial value as fallback instead of parent"
  src/lib/extended/show-hide/show-hide.ts
  src/lib/extended/show-hide/show.spec.ts
Labels: cla: yes

#1252 fix(show-hide): set explicit display fallback for SSR
  src/lib/extended/show-hide/show-hide.ts
  src/lib/extended/show-hide/show.spec.ts
Labels: cla: yes

#1254 chore: update StackBlitz links
  .github/ISSUE_TEMPLATE/Bug.md
  CONTRIBUTING.md
  README.md
Labels: cla: yes, pr: merge safe

#1257 chore: update to 9.0.0-beta.31 with changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: merge safe

#1260 fix(core): add generic type to ModuleWithProviders to support v10
  src/lib/module.ts
Labels: cla: yes

#1265 fix(mock-match-media): ensure overlapping breakpoints are activated
  src/lib/core/match-media/mock/mock-match-media.spec.ts
  src/lib/core/match-media/mock/mock-match-media.ts
Labels: cla: yes

#1261 build: upgrade to Angular v10, CDK v10, and TypeScript 3.9
  package.json
  src/apps/demo-app/angular.json
  src/apps/demo-app/package.json
  src/apps/demo-app/tsconfig.json
  src/apps/hello-world/angular.json
  src/apps/hello-world/package.json
  src/apps/hello-world/tsconfig.json
  src/apps/universal-app/angular.json
  src/apps/universal-app/package.json
  src/apps/universal-app/tsconfig.json
  src/lib/package.json
  src/lib/tsconfig-tests.json
  tools/gulp/util/task-helpers.ts
  yarn.lock
Labels: build, cla: yes, pr: merge safe
