Repository angular/flex-layout, pull requests merged in 2020-02, with the labels that each got.

#1191 build: avoid incorrect provider definition renaming
  src/lib/core/tsconfig-build.json
  src/lib/extended/tsconfig-build.json
  src/lib/flex/tsconfig-build.json
  src/lib/grid/tsconfig-build.json
  src/lib/server/tsconfig-build.json
  src/lib/tsconfig-build.json
  tools/package-tools/build-package.ts
  tools/package-tools/compile-entry-point.ts
Labels: build, cla: yes, pr: merge safe, pr: needs review

#1192 chore: update to 9.0.0-beta.29 with changelog
  CHANGELOG.md
  package.json
Labels: cla: yes, pr: merge safe

#1206 Broken Url
  docs/documentation/_Sidebar.md
Labels: cla: yes
